export default {
  black: "#000",
  blue: "#00a",
  green: "#0a0",
  cyan: "#0aa",
  red: "#a00",
  magenta: "#a0a",
  brown: "#a50",
  lightGray: "#aaa",
  darkGray: "#555",
  lightBlue: "#55f",
  lightGreen: "#5f5",
  lightCyan: "#5ff",
  lightRed: "#f55",
  lightMagenta: "#f5f",
  yellow: "#ff5",
  white: "#fff",
};
